version: "3"
services:

              
  app: 
     image: sajaweb/realestate_app
     container_name: realestateapp
     volumes: 
      - /app/images:/app/images
      - /app/document:/app/document
      - /app/slider:/app/slider
 
     environment:
       - APIKEY=${SMS_KEY}  
       - DBPASS=${DATABASE_PASS}
       - TERMINALID=${TERMINAL_ID}
       - MERCHANTID=${MERCHANT_ID}
       - SADADKEY=${SADAD_KEY}
     build:  
        context: .
        dockerfile: Dockerfile    
     ports: 
      - "5001:8000"
   #   depends_on:
   #    - mongo
 
